name: Marketing
on:
  push:
    branches:
      - main
    paths:
      - "packages/marketing/**"
defaults:
  run:
    working-directory: packages/marketing
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install marketing dependencies
        run:  npm install    
        working-directory: packages/marketing
     
      - name: Build marketing
        run: npm run build
      - uses: shinyinc/action-aws-cli@v1
      - name: Upload to S3
        run: aws s3 cp dist s3://${{ secrets.AWS_S3_BUCKET }}/marketing/latest/ --recursive
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Invalidate Cloudfront
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION_ID }} --paths "/marketing/latest/remoteEntry.js"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: eu-central-1